"""empty message

Revision ID: 01a8fc24afa3
Revises: f18a3c30e476
Create Date: 2020-05-18 09:54:11.313026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a8fc24afa3'
down_revision = 'f18a3c30e476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element', sa.Column('link_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('element', 'link_url')
    # ### end Alembic commands ###
