"""empty message

Revision ID: 0fc9a6329571
Revises: de5ecaea0d20
Create Date: 2020-04-05 18:36:13.408970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc9a6329571'
down_revision = 'de5ecaea0d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element', sa.Column('attached_thumb', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('element', 'attached_thumb')
    # ### end Alembic commands ###
